name: Minimal Android CI Workflow
 
on:
  #push:
  #  branches:
  #    - master
  #    - develop
  #  paths-ignore:
  #    - '.github/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - develop
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - run: echo $ANIME_GOOGLE_SERVICES_JSON > animeworld/google-services.json
        env:
          ANIME_GOOGLE_SERVICES_JSON: ${{ secrets.ANIME_SERVICES }}
      - run: echo $MANGA_GOOGLE_SERVICES_JSON > mangaworld/google-services.json
        env:
          MANGA_GOOGLE_SERVICES_JSON: ${{ secrets.MANGA_SERVICES }}
      - run: echo $NOVEL_GOOGLE_SERVICES_JSON > novelworld/google-services.json
        env:
          NOVEL_GOOGLE_SERVICES_JSON: ${{ secrets.NOVEL_SERVICES }}
      - run: echo $ANIME_TV_GOOGLE_SERVICES_JSON > animeworldtv/google-services.json
        env:
          ANIME_TV_GOOGLE_SERVICES_JSON: ${{ secrets.ANIME_TV_SERVICES }}
      - run: echo OTAKU_MANAGER_GOOGLE_SERVICES_JSON > otakumanager/google-services.json
        env:
          OTAKU_MANAGER_GOOGLE_SERVICES_JSON: ${{ secrets.OTAKU_MANAGER_SERVICES }}

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: animeworld/build/outputs/apk/debug/animeworld-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: mangaworld/build/outputs/apk/debug/mangaworld-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: novelworld/build/outputs/apk/debug/novelworld-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: animeworldtv/build/outputs/apk/debug/animeworldtv-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: otakumanager/build/outputs/apk/debug/otakumanager-debug.apk
