name: Minimal Android CI Workflow

on:
  #push:
  #  branches:
  #    - master
  #    - develop
  #  paths-ignore:
  #    - '.github/**'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - develop
      - master
  workflow_dispatch:
    inputs:
      build_animeworld:
        description: 'Build AnimeWorld?'
        required: true
        default: 'true'
      build_animeworldtv:
        description: 'Build AnimeWorldTV?'
        required: true
        default: 'true'
      build_mangaworld:
        description: 'Build MangaWorld?'
        required: true
        default: 'true'
      build_novelworld:
        description: 'Build NovelWorld?'
        required: true
        default: 'true'

jobs:
  mangaworld:
    uses: ./.github/workflows/mangaworld_build.yml
    if: github.event.inputs.build_mangaworld == 'true' || github.event_name == 'pull_request'
    secrets: inherit # pass all secrets
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-manga
      cancel-in-progress: true

  animeworld:
    uses: ./.github/workflows/animeworld_build.yml
    if: github.event.inputs.build_animeworld == 'true' || github.event_name == 'pull_request'
    secrets: inherit # pass all secrets
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-anime
      cancel-in-progress: true

  animeworldtv:
    uses: ./.github/workflows/animeworldtv_build.yml
    if: github.event.inputs.build_animeworldtv == 'true' || github.event_name == 'pull_request'
    secrets: inherit # pass all secrets
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-animetv
      cancel-in-progress: true

  novelworld:
    uses: ./.github/workflows/novelworld_build.yml
    if: github.event.inputs.build_novelworld == 'true' || github.event_name == 'pull_request'
    secrets: inherit # pass all secrets
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-novel
      cancel-in-progress: true