name: Release Workflow
 
on:
  workflow_dispatch:
   

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - run: echo $ANIME_GOOGLE_SERVICES_JSON > animeworld/google-services.json
        env:
          ANIME_GOOGLE_SERVICES_JSON: ${{ secrets.ANIME_SERVICES }}
      - run: echo $MANGA_GOOGLE_SERVICES_JSON > mangaworld/google-services.json
        env:
          MANGA_GOOGLE_SERVICES_JSON: ${{ secrets.MANGA_SERVICES }}
      - run: echo $NOVEL_GOOGLE_SERVICES_JSON > novelworld/google-services.json
        env:
          NOVEL_GOOGLE_SERVICES_JSON: ${{ secrets.NOVEL_SERVICES }}
          
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#       - name: Build APK
#         run: bash ./gradlew assembleRelease --stacktrace

      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: 6.7.1
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: manga_sign
        with:
          releaseDirectory: mangaworld/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: Signed Manga App
          path: mangaworld/build/outputs/apk/release/*.apk
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: anime_sign
        with:
          releaseDirectory: animeworld/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}    
          
      - uses: actions/upload-artifact@v2
        with:
          name: Signed Anime App
          path: animeworld/build/outputs/apk/release/*.apk
          
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: novel_sign
        with:
          releaseDirectory: novelworld/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}    
          
      - uses: actions/upload-artifact@v2
        with:
          name: Signed Novel App
          path: novelworld/build/outputs/apk/release/*.apk
          

#       - name: Upload APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: apk
#           path: animeworld/build/outputs/apk/debug/animeworld-debug.apk 
#       - name: Upload APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: apk
#           path: mangaworld/build/outputs/apk/debug/mangaworld-debug.apk 
#       - name: Upload APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: apk
#           path: novelworld/build/outputs/apk/debug/novelworld-debug.apk 
          
  release:
    name: Release APK
    needs: apk
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
     - name: Download APK from build
       uses: actions/download-artifact@v1
       with:
         name: apk  
     - name: Get tag name
       id: get_tag_name
       run: |
         set -x
         echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
#      - name: Create Release
#        id: create_release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.VERSION_TAG }}
#          name: Release ${{ env.VERSION_TAG }}
#          files: |
#             apk/mangaworld-debug.apk
#             apk/animeworld-debug.apk
#             apk/novelworld-debug.apk
